### ISSUE TITLE
Seeking help about RAFT model

### ISSUE THREAD

**Issue by lpc-eol** [hermosayhl/image_processing#1]
从知乎 图像处理基础（十八）光流中的 warp 与遮挡检测 而来，看了您对wrap的分析清楚了许多。
目前我希望对RAFT 作自监督学习， 但我对光流模型不是很熟悉，希望能请教您。

**Comment by hermosayhl** [comment]
你好，我不是专门搞光流的，我只是在实习的公司用到了光流，所以用到了这一步。光流的话，我建议从孙德清的论文开始看起，PWC-Net就是他的作品，谷歌学术上你可以找他的很多论文，他做光流比较专业

**Comment by lpc-eol** [comment]
> 你好，我不是专门搞光流的，我只是在实习的公司用到了光流，所以用到了这一步。光流的话，我建议从孙德清的论文开始看起，PWC-Net就是他的作品，谷歌学术上你可以找他的很多论文，他做光流比较专业

好的感谢！
